using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TileGamePrototype
{
    public static class LevelContainerClass
    {
        //Example Level

        //Example Level
        //static levelInfo tinyLevel = new levelInfo(2, 2, new TileTypes[,] { { TileTypes.Grass, TileTypes.Water }, { TileTypes.Player, TileTypes.Tree } }, new List<ObjectiveTypes> { }, null, 1, 2, 3);

        //Level 1
        static TileTypes[,] level1 = new TileTypes[4, 4]{ { TileTypes.Grass, TileTypes.Bush, TileTypes.Water, TileTypes.Water },
                                                           { TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water},
                                                           { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Sticks},
                                                           { TileTypes.Player, TileTypes.Rocks, TileTypes.Grass, TileTypes.Grass} };
        static levelInfo level1Info = new levelInfo(level1.GetLength(0), level1.GetLength(1), level1, new List<ObjectiveTypes> { ObjectiveTypes.FindFood }, null, 4, 5, 8);

        //Level 2
        static TileTypes[,] level2 = new TileTypes[4, 4]{ { TileTypes.Home, TileTypes.Tree, TileTypes.Rocks, TileTypes.Sticks },
                                                           { TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass},
                                                           { TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Water},
                                                           { TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Player} };

        static levelInfo level2Info = new levelInfo(level2.GetLength(0), level2.GetLength(1), level2, new List<ObjectiveTypes> { ObjectiveTypes.ReturnHome }, null, 9, 11, 15);

        //Level 3
        static TileTypes[,] level3 = new TileTypes[4, 4]{ { TileTypes.Home, TileTypes.Water, TileTypes.Grass, TileTypes.Tree },
                                                           { TileTypes.Grass, TileTypes.Water, TileTypes.Player, TileTypes.Grass},
                                                           { TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Sticks},
                                                           { TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Rocks} };
        static levelInfo level3Info = new levelInfo(level3.GetLength(0), level3.GetLength(1), level3, new List<ObjectiveTypes> { ObjectiveTypes.ReturnHome }, null, 11, 13, 16);

        //Level 4
        static TileTypes[,] level4 = new TileTypes[4, 4]{ { TileTypes.Player, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass },
                                                           { TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass},
                                                           { TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass},
                                                           { TileTypes.Sticks, TileTypes.Bush, TileTypes.Rocks, TileTypes.Home} };
        static levelInfo level4Info = new levelInfo(level4.GetLength(0), level4.GetLength(1), level4, new List<ObjectiveTypes> { ObjectiveTypes.FindFood, ObjectiveTypes.ReturnHome }, null, 11, 13, 16);


        //Level 5 - First relic level
        static TileTypes[,] level5 = new TileTypes[6, 6] {{TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Treasure, TileTypes.Player},
                                                         {TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water},
                                                         {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Sticks},
                                                         {TileTypes.Grass, TileTypes.Bridge, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass},
                                                         {TileTypes.Grass, TileTypes.Water, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass},
                                                         {TileTypes.Rocks, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass}};
        static levelInfo level5Info = new levelInfo(level5.GetLength(0), level5.GetLength(1), level5, new List<ObjectiveTypes> { ObjectiveTypes.ObtainRelic }, null, 32, 36, 45, new Relic(global::TileGamePrototype.Properties.Resources.TerracotaWarrior));

        //Level 6
        static TileTypes[,] level6 = new TileTypes[8, 8] {{TileTypes.Player, TileTypes.Grass, TileTypes.Passive, TileTypes.Rocks, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Sticks},
                                                         {TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree},
                                                         {TileTypes.Grass, TileTypes.Grass, TileTypes.Sticks, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass},
                                                         {TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Home, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass},
                                                         {TileTypes.Grass, TileTypes.Rocks, TileTypes.Passive, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water},
                                                         {TileTypes.Passive, TileTypes.Passive, TileTypes.Water, TileTypes.Rocks, TileTypes.Water, TileTypes.Sticks, TileTypes.Water, TileTypes.Grass},
                                                         {TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                         {TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass}};
        static levelInfo level6Info = new levelInfo(level6.GetLength(0), level6.GetLength(1), level6, new List<ObjectiveTypes> { ObjectiveTypes.ReturnHome }, null, 29, 43, 50);

        //Level 7
        static TileTypes[,] level7 = new TileTypes[12, 12] {{ TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Player },
                                                            { TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Grass },
                                                            { TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Grass },
                                                            { TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Grass },
                                                            { TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Grass },
                                                            { TileTypes.Passive, TileTypes.Passive, TileTypes.Water, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Water, TileTypes.Passive, TileTypes.Tree, TileTypes.Passive, TileTypes.Water, TileTypes.Passive },
                                                            { TileTypes.Passive, TileTypes.Passive, TileTypes.Water, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Tree, TileTypes.Passive, TileTypes.Water, TileTypes.Passive },
                                                            { TileTypes.Passive, TileTypes.Water, TileTypes.Water, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Water, TileTypes.Passive },
                                                            { TileTypes.Passive, TileTypes.Water, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Water, TileTypes.Passive },
                                                            { TileTypes.Water, TileTypes.Water, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Water, TileTypes.Water },
                                                            { TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Home }};
        static levelInfo level7Info = new levelInfo(level7.GetLength(0), level7.GetLength(1), level7, new List<ObjectiveTypes> { ObjectiveTypes.ReturnHome }, null, 35, 43, 50);


        //Level 8
        static TileTypes[,] level8 = new TileTypes[4, 4] { { TileTypes.Player, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree },
                                                                { TileTypes.Sticks, TileTypes.Rocks, TileTypes.Bush, TileTypes.Water },
                                                                { TileTypes.Water, TileTypes.Bridge, TileTypes.Passive, TileTypes.Water},
                                                                { TileTypes.Hostile, TileTypes.Grass, TileTypes.Bush, TileTypes.Home} };
        static levelInfo level8Info = new levelInfo(level8.GetLength(0), level8.GetLength(1), level8, new List<ObjectiveTypes> { ObjectiveTypes.FindFood, ObjectiveTypes.FindFood, ObjectiveTypes.ReturnHome }, null, 10, 11, 15);

        //Level 9
        static TileTypes[,] level9 = new TileTypes[6,6] { { TileTypes.Tree, TileTypes.Tree, TileTypes.Sticks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Player },
                                                                { TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                                { TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass },
                                                                { TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                                { TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Passive },
                                                                { TileTypes.Home, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass }};
        static levelInfo level9Info = new levelInfo(level9.GetLength(0), level9.GetLength(1), level9, new List<ObjectiveTypes> { ObjectiveTypes.ReturnHome }, null, 14, 17, 21 );        

        //Second Relic Level
        static TileTypes[,] level10 = new TileTypes[16, 16] { { TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Water, TileTypes.Rocks, TileTypes.Rocks },
                                                            { TileTypes.Water, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Water, TileTypes.Rocks, TileTypes.Grass },
                                                            { TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Water, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Bridge, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Bridge, TileTypes.Water, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Treasure, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Sticks, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Hostile },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Sticks, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Bush },
                                                            { TileTypes.Passive, TileTypes.Grass, TileTypes.Sticks, TileTypes.Home, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Passive, TileTypes.Grass, TileTypes.Sticks, TileTypes.Sticks, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree },
                                                            { TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Sticks, TileTypes.Sticks, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree },
                                                            { TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Sticks, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Bridge, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree },
                                                            { TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Player } };
        static levelInfo level10Info = new levelInfo(level10.GetLength(0), level10.GetLength(1), level10, new List<ObjectiveTypes> { ObjectiveTypes.ObtainRelic, ObjectiveTypes.ReturnHome, ObjectiveTypes.CollectItem, ObjectiveTypes.CollectItem }, new List<ItemTypes> { ItemTypes.Berries, ItemTypes.Meat }, 114, 120, 150, new Relic(global::TileGamePrototype.Properties.Resources.FabergéEgg));

        //Level 11

        static TileTypes[,] level11 = new TileTypes[8, 8] { { TileTypes.Sticks, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Player, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass },
                                                            { TileTypes.Water, TileTypes.Rocks, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass },
                                                            { TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Bush, TileTypes.Water, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass },
                                                            { TileTypes.Home, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive } };
        static levelInfo level11Info = new levelInfo(level11.GetLength(0), level11.GetLength(1), level11, new List<ObjectiveTypes> { ObjectiveTypes.FindFood, ObjectiveTypes.FindFood, ObjectiveTypes.ReturnHome }, null, 56, 60, 75);


        //Level 12
        static TileTypes[,] level12 = new TileTypes[24, 24]{  { TileTypes.Player, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Home },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree },
                                                    { TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree },
                                                    { TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Hostile, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Hostile, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass },
                                                    { TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Passive, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Passive, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Hostile, TileTypes.Tree, TileTypes.Grass, TileTypes.Hostile, TileTypes.Tree, TileTypes.Passive, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Hostile, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Passive, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Passive, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree },
                                                    { TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Hostile, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Hostile, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree },
                                                    { TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree },
                                                    { TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree },
                                                    { TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Tree, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Bridge, TileTypes.Bridge, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Bridge, TileTypes.Bridge, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree },
                                                    { TileTypes.Grass, TileTypes.Sticks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree },
                                                    { TileTypes.Sticks, TileTypes.Sticks, TileTypes.Sticks, TileTypes.Sticks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree }};
        static levelInfo level12Info = new levelInfo(level12.GetLength(0), level12.GetLength(1), level12, new List<ObjectiveTypes> { ObjectiveTypes.FindFood, ObjectiveTypes.FindFood, ObjectiveTypes.FindFood, ObjectiveTypes.FindFood, ObjectiveTypes.FindFood, ObjectiveTypes.ReturnHome }, null, 152, 160, 200);

        //Level 13

        static TileTypes[,] level13 = new TileTypes[24, 24] {  { TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Tree, TileTypes.Player },
                                                    { TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Rocks, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Sticks, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree, TileTypes.Grass },
                                                    { TileTypes.Rocks, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                    { TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree },
                                                    { TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Rocks, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Grass, TileTypes.Passive, TileTypes.Passive, TileTypes.Tree, TileTypes.Tree, TileTypes.Tree, TileTypes.Grass, TileTypes.Tree },
                                                    { TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water },
                                                    { TileTypes.Grass, TileTypes.Bush, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Bush, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water },
                                                    { TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                    { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water },
                                                    { TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Bush, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Sticks },
                                                    { TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                    { TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass },
                                                    { TileTypes.Home, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Bush, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Bush, TileTypes.Water, TileTypes.Water, TileTypes.Sticks, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass } };

        static levelInfo level13Info = new levelInfo(level13.GetLength(0), level13.GetLength(1), level13, new List<ObjectiveTypes> { ObjectiveTypes.FindFood, ObjectiveTypes.ReturnHome }, null, 447, 460, 500);


        //Level 14
        static TileTypes[,] level14 = new TileTypes[32, 32] { { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,     TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile },
                                                            { TileTypes.Grass,  TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,         TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass,      TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass,  TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass,     TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,      TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,   TileTypes.Hostile,      TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,     TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,    TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,         TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass,   TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass,    TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,         TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,     TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,    TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass },
                                                            { TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Hostile,    TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,     TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass,    TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,          TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,         TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass },
                                                            { TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass,     TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass,     TileTypes.Home, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,         TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass,      TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,          TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,       TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass,     TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass,       TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Player, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,    TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass,      TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,          TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass,     TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass,    TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,          TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,         TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,      TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,      TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,         TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,    TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass,       TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass,       TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass,    TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,      TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile,      TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass },
                                                            { TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Hostile, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,       TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass,        TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Hostile } };

        static levelInfo level14Info = new levelInfo(level14.GetLength(0), level14.GetLength(1), level14, new List<ObjectiveTypes> { ObjectiveTypes.ReturnHome }, null, 249, 261, 300);



        //Final Relic Level
        static TileTypes[,] level15 = new TileTypes[32, 32]  {{TileTypes.Treasure, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Rocks},
                                                            {TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Tree, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Sticks, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Sticks, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Rocks, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Rocks, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Tree},
                                                            {TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Water, TileTypes.Grass, TileTypes.Water, TileTypes.Water},
                                                            {TileTypes.Sticks, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Grass, TileTypes.Water, TileTypes.Grass, TileTypes.Grass, TileTypes.Player}};

        static levelInfo level15Info = new levelInfo(level15.GetLength(0), level15.GetLength(1), level15, new List<ObjectiveTypes> { ObjectiveTypes.ObtainRelic }, null, 557, 600, 700, new Relic(global::TileGamePrototype.Properties.Resources.TuckersCross));


        //Levels array
        static levelInfo[] levelInfoArray = new levelInfo[] { level1Info, level2Info, level3Info, level4Info, level5Info, level6Info, level7Info, level8Info, level9Info, level10Info, level11Info, level12Info, level13Info, level14Info, level15Info };

        //Initialise all the extra level data
        public static void initAllLevels()
        {
            Console.WriteLine("Levels Are Initialised");
            //Level4 Animals
            Dictionary<System.Drawing.Point, int[]> level4paths = new Dictionary<System.Drawing.Point, int[]>();
            level4paths.Add(new System.Drawing.Point(2, 2), new int[] { 1, 1, 3, 3 });
            level4Info.setUpAnimals(level4paths);

            //Level 5 animals
            Dictionary<System.Drawing.Point, int[]> level5paths = new Dictionary<System.Drawing.Point, int[]>();
            level5paths.Add(new System.Drawing.Point(4, 2), new int[] { 2, 2, 1, 1, 4, 4, 3, 3 });
            //level5paths.Add(new System.Drawing.Point(2, 4), new int[] { 3, 3, 1, 1 });
            level5Info.setUpAnimals(level5paths);

            //Level 5 Relic
            level5Info.relic.info = "The Terracotta Warriors were discovered by farmers in 1974. They depict chinese military personnel. Over 8000 statues were buried in the tomb of Qin Shi Huang, the first emperor of China, around 200 B.C.\nSee en.wikipedia.org/wiki/Terracotta_Army and goo.gl/tYba3a for more information";

            //Level 7 animals
            Dictionary<System.Drawing.Point, int[]> level7paths = new Dictionary<System.Drawing.Point, int[]>();
            level7paths.Add(new System.Drawing.Point(11, 0), new int[] { 2, 2, 1, 2, 1, 1, 1, 2, 3, 2, 2, 1, 2, 1, 1, 1, 1, 1, 4, 4, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4 });
            level7Info.setUpAnimals(level7paths);

            //Level 10 animals
            Dictionary<System.Drawing.Point, int[]> level10paths = new Dictionary<System.Drawing.Point, int[]>();
            level10paths.Add(new System.Drawing.Point(9, 15), new int[] { 4, 3, 3, 2, 4, 1, 1, 2 });
            level10Info.setUpAnimals(level10paths);

            //Level 10 Relic
            level10Info.relic.info = "Fabergé eggs are a set of jewelled eggs originating in Russia. The first egg was crafted in 1885, this was called the Hen Egg. 65 eggs were created between 1885 and 1917. There are 7 eggs that have been lost.\nSee en.wikipedia.org/wiki/Fabergé_egg and goo.gl/SoKETf for more information";

            Dictionary<System.Drawing.Point, int[]> level11paths = new Dictionary<System.Drawing.Point, int[]>();
            level11paths.Add(new System.Drawing.Point(7, 1), new int[] { 2, 2, 1, 1, 1, 4, 4, 4, 3, 3, 2, 3, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4 });
            level11Info.setUpAnimals(level11paths);

            //Level 11 Animals
            Dictionary<System.Drawing.Point, int[]> level12paths = new Dictionary<System.Drawing.Point, int[]>();
            level12paths.Add(new System.Drawing.Point(9, 9), new int[] {3, 3, 3, 3, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 3, 3, 3, 3 });
            level12Info.setUpAnimals(level12paths);

            //Level 15 Relic
            level15Info.relic.info = "The Tucker's Cross is a relic from Central America. It was found in a wrecked Spanished galleon from 1594. It was stolen from the museum in Bermuda where it was being displayed sometime between 1959 and 1975.\nSee en.wikipedia.org/wiki/Tucker%27s_Cross and goo.gl/bmqB7B for more information.";

        }

        //Returns level data
        public static levelInfo extractLevelInfo(int level)
        {
            return levelInfoArray[level];
        }

        //Returns the number of levels
        public static int GetLevelCount()
        {
            return levelInfoArray.Length;
        }

        public struct rank
        {
            public int movesTaken; //Lowest number of moves
            public int medal; //1 - Gold, 2 - Silver, 3 - Bronze, 4 - None
        }

        //Class containing all the data for the levels
        public class levelInfo
        {
            //Size
            public int width;
            public int height;

            //Depricated cave variables
            public bool containsCave;
            public int caveWidth;
            public int caveHeight;

            //Arrays of tiles
            public TileTypes[,] surface;
            public TileTypes[,] cave;

            //Depricated cave identifiers
            public int[] surfaceCaveId;
            public int[] caveCaveId;

            //Level objectives
            public List<ObjectiveTypes> objectives;
            public List<ItemTypes> itemsToCollect;

            //Level relic - if applicable
            public Relic relic;

            //Scores
            public int gold;
            public int silver;
            public int bronze;

            //Animals paths
            public Dictionary<System.Drawing.Point, int[]> paths;

            //Constructor
            public levelInfo(
                int _width, 
                int _height, 
                TileTypes[,] _surface,
                List<ObjectiveTypes> _objectives,
                List<ItemTypes> _itemsToCollect,
                int _gold, int _silver, int _bronze,
                Relic _relic = null
                )
            {
                this.width = _width;
                this.height = _height;
                this.surface = _surface;
                this.objectives = _objectives;
                this.itemsToCollect = _itemsToCollect;
                this.relic = _relic;
                this.gold = _gold;
                this.bronze = _bronze;
                this.silver = _silver;
            }

            //Set up animal paths
            public void setUpAnimals(Dictionary<System.Drawing.Point, int[]> _paths)
            {
                paths = _paths;
            }

            //Depricated cave set up
            public void setUpCave(
                int _caveWidth, 
                int _caveHeight, 
                TileTypes[,] _cave, 
                int[] _surfaceCaveId, 
                int[] _caveCaveId)
            { 
                this.containsCave = true;
                this.caveWidth = _caveWidth;
                this.caveHeight = _caveHeight;
                this.cave = _cave;
                this.surfaceCaveId = _surfaceCaveId;
                this.caveCaveId = _caveCaveId;
            }
        }
    }
}
